"""
Supabase database table schema definitions.

These Pydantic models represent the structure of PostgreSQL tables in Supabase.
Each model corresponds to a table that will be created during initialization.

Tables:
- received_emails: Raw emails from Gmail
- received_email_attachments: Email attachments
- drafted_emails: LLM-generated drafts awaiting approval
- sent_emails: Confirmed sent emails
- validation_logs: Pipeline execution logs
"""

from datetime import datetime
from enum import Enum
from typing import Any, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class BaseDBModel(BaseModel):
    """Base model with common configurations for database schemas."""

    model_config = ConfigDict(str_strip_whitespace=True)
    id: Optional[str] = Field(
        default=None, description="Primary key (UUID, generated by DB)"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata (JSON)"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When inserted"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow, description="When last updated"
    )


class EmailProcessingMode(str, Enum):
    incoming = "incoming"
    outgoing = "outgoing"


class EmailAttachment(BaseDBModel):
    """Schema for 'received_email_attachments' table.

    Stores attachment metadata for attachments in received_emails.
    """

    email_type: Literal["incoming", "outgoing"] = Field(
        default="incoming", description="Type of email: received or sent"
    )
    email_id: str = Field(..., description="FK to received_emails.email_id")
    filename: str = Field(..., description="Attachment filename")
    size_bytes: int = Field(..., description="Attachment size", ge=0)
    mime_type: Optional[str] = Field(default=None, description="MIME type")
    sha256: Optional[str] = Field(
        default=None, description="SHA-256 hash of attachment content"
    )
    storage_path: Optional[str] = Field(
        default=None, description="Path in cloud storage (if stored)"
    )


class BaseEmail(BaseDBModel):
    """Base model for email-related IOFs."""

    model_config = ConfigDict(str_strip_whitespace=True)

    subject: str = Field(..., description="Email subject line")
    body: str = Field(..., description="Email body content")
    from_email: str = Field(..., description="Sender email address")
    to_emails: list[str] = Field(..., description="List of recipient email addresses")
    cc_emails: list[str] = Field(
        default_factory=list, description="List of CC recipient email addresses"
    )
    bcc_emails: list[str] = Field(
        default_factory=list, description="List of BCC recipient email addresses"
    )
    attachments: list[EmailAttachment] = Field(
        default_factory=list, description="List of attachments"
    )

    @field_validator("from_email", "to_emails", "cc_emails", "bcc_emails")
    @classmethod
    def validate_emails(cls, v: Any) -> Any:
        """Validate email format."""
        if isinstance(v, list):
            for email in v:
                if "@" not in email:
                    raise ValueError(f"Invalid email: {email}")
            return v
        if "@" not in v:
            raise ValueError(f"Invalid email: {v}")
        return v

    def summary(self) -> str:
        """Generate a brief summary of the email."""
        return f"Email from {self.from_email} to {', '.join(self.to_emails)} with subject '{self.subject}' \n\n *Body:*\n {self.body}"


class ReceivedEmail(BaseEmail):
    """Schema for 'received_emails' table in Supabase.

    Stores parsed, deduplicated emails from Gmail. Primary table for email history.
    """

    type: Literal["incoming"] = Field(
        default="incoming",
        description="Email type: incoming or outgoing",
    )
    message_id: str = Field(..., description="Gmail message ID")
    thread_id: Optional[str] = Field(default=None, description="Gmail thread ID")
    received_at: datetime = Field(..., description="When received")
    labels: list[str] = Field(
        default_factory=list, description="Gmail labels (JSON array)"
    )
    is_read: bool = Field(default=False)
    classification: Optional[str] = Field(
        default=None, description="Classification: crm, customer_success, spam"
    )
    classification_confidence: Optional[float] = Field(
        default=None, description="Classification confidence", ge=0.0, le=1.0
    )


# ============================================================================
# DraftedEmails Table
# ============================================================================


class DraftedEmail(BaseEmail):
    """Schema for 'drafted_emails' table.

    Stores LLM-generated response drafts awaiting human approval before sending.
    """

    model_used: Optional[str] = Field(
        default=None, description="LLM model (e.g., gpt-4o-mini)"
    )
    tokens_used: Optional[int] = Field(
        default=None, description="Tokens consumed", ge=0
    )
    confidence: float = Field(
        default=1.0, description="Draft quality confidence", ge=0.0, le=1.0
    )
    approval_status: str = Field(
        default="pending",
        description="Status: pending, approved, rejected, sent",
    )
    approved_by: Optional[str] = Field(default=None, description="User who approved")
    approved_at: Optional[datetime] = Field(
        default=None, description="Approval timestamp"
    )
    rejection_reason: Optional[str] = Field(
        default=None, description="If rejected, why"
    )

    # Indexes: email_id (FK), approval_status, created_at


# ============================================================================
# SentEmails Table
# ============================================================================


class SentEmail(BaseEmail):
    """Schema for 'sent_emails' table.

    Stores confirmed sent emails. Created after successful send via Gmail API.
    """

    type: Literal["outgoing"] = Field(
        default="outgoing",
        description="Email type: incoming or outgoing",
    )
    in_reply_to: Optional[str] = Field(default=None, description="Email ID this email is replying to")
    drafted_email_id: Optional[str] = Field(
        default=None, description="FK to drafted_emails.id (if from draft)"
    )
    message_id: str = Field(..., description="Gmail message ID of sent email")
    labels: list[str] = Field(
        default_factory=list, description="Gmail labels (JSON array)"
    )
    thread_id: str = Field(..., description="Gmail thread ID")
    sent_status: str = Field(..., description="Status: sent, bounced, delivery_failed")
    sent_at: datetime = Field(..., description="When sent")


# ============================================================================
# Opportunities Tables
# ============================================================================


class Opportunity(BaseModel):
    """Schema for 'opportunities' table."""

    model_config = ConfigDict(str_strip_whitespace=True)

    id: Optional[str] = Field(default=None, description="Primary key (UUID)")
    title: str = Field(..., description="Opportunity title")
    summary: Optional[str] = Field(default=None, description="Opportunity summary")
    embedding: Optional[list[float]] = Field(
        default=None, description="1536-dimensional vector (pgvector type)"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When created"
    )

    @field_validator("embedding", mode="before")
    @classmethod
    def parse_pgvector_embedding(cls, v: Any) -> Any:
        """Parse pgvector string representation to list of floats.

        Supabase returns pgvector columns as strings like '[0.1,0.2,0.3]'.
        This validator converts them to actual Python lists.
        """
        if v is None:
            return None
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            # Parse string representation: '[0.1,0.2,0.3]' -> [0.1, 0.2, 0.3]
            v = v.strip()
            if v.startswith("[") and v.endswith("]"):
                v = v[1:-1]  # Remove brackets
            if not v:  # Empty string after removing brackets
                return None
            try:
                return [float(x.strip()) for x in v.split(",") if x.strip()]
            except (ValueError, AttributeError) as e:
                raise ValueError(f"Invalid embedding format: {e}")
        return v


class Contact(BaseModel):
    """Schema for 'contacts' table."""

    model_config = ConfigDict(str_strip_whitespace=True)

    id: Optional[str] = Field(default=None, description="Primary key (UUID)")
    name: str = Field(..., description="Contact name")
    email: str = Field(..., description="Contact email")
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When created"
    )


class OpportunityContactLink(BaseModel):
    """Schema for 'oppportunity_contact' join table."""

    model_config = ConfigDict(str_strip_whitespace=True)

    opportunity_id: str = Field(..., description="FK to opportunities.id")
    contact_id: str = Field(..., description="FK to contacts.id")


# ============================================================================
# ValidationLogs Table
# ============================================================================


class ValidationLog(BaseModel):
    """Schema for 'validation_logs' table.

    Complete audit trail of pipeline execution for each email.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    id: Optional[str] = Field(default=None, description="Primary key (UUID)")
    email_id: str = Field(..., description="Email being processed")
    pipeline_execution_id: str = Field(
        ..., description="Unique ID for this execution run"
    )
    total_duration_seconds: float = Field(
        ..., description="Total execution time", ge=0.0
    )
    final_status: str = Field(
        ..., description="Final status: success, partial_success, failure"
    )
    stage_logs: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Logs from each stage: stage, status, message, details (JSON array)",
    )
    errors: list[str] = Field(
        default_factory=list, description="Critical errors (JSON array)"
    )
    warnings: list[str] = Field(
        default_factory=list, description="Non-critical warnings (JSON array)"
    )
    summary: str = Field(..., description="Human-readable summary")
    kg_nodes_created: int = Field(default=0, description="KG nodes created", ge=0)
    kg_edges_created: int = Field(default=0, description="KG edges created", ge=0)
    rag_vectors_upserted: int = Field(
        default=0, description="RAG vectors upserted", ge=0
    )
    model_config_used: dict[str, Any] = Field(
        default_factory=dict, description="Model config snapshot (JSON)"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When logged"
    )

    # Indexes: email_id (FK), pipeline_execution_id, final_status, created_at


# ============================================================================
# KGEntities Table (Optional - Caching of KG nodes)
# ============================================================================


class KGEntity(BaseModel):
    """Schema for 'kg_entities' table (optional, for caching KG node info).

    Stores cached entity information from Neo4j/Graphiti for quick lookup.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    id: Optional[str] = Field(default=None, description="Primary key (UUID)")
    entity_id: str = Field(..., description="KG node ID (from Neo4j)")
    entity_type: str = Field(
        ..., description="Type: Company, Contact, Opportunity, etc."
    )
    entity_name: str = Field(..., description="Entity name/value")
    entity_data: dict[str, Any] = Field(
        default_factory=dict, description="Full entity JSON"
    )
    last_seen_in_email: Optional[str] = Field(
        default=None, description="Last email mentioning this entity"
    )
    mention_count: int = Field(default=0, description="Total mentions", ge=0)
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When cached"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow, description="When last updated"
    )

    # Indexes: entity_id (UNIQUE), entity_type, entity_name


# ============================================================================
# RAGVectors Table (Supabase pgvector)
# ============================================================================


class RAGVector(BaseModel):
    """Schema for 'rag_vectors' table (pgvector in Supabase).

    Stores vector embeddings for email content and context for semantic search.
    Uses pgvector extension. Vectors are 1536-dimensional (OpenRouter standard).
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    id: Optional[str] = Field(default=None, description="Primary key (UUID)")
    email_id: str = Field(..., description="FK to received_emails.email_id")
    chunk_index: int = Field(
        default=0, description="Chunk index if email split into multiple", ge=0
    )
    content: str = Field(..., description="Text content that was embedded")
    embedding: list[float] = Field(
        ..., description="1536-dimensional vector (pgvector type)"
    )
    content_type: str = Field(
        default="email_body",
        description="Type: email_body, email_subject, context",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata: tokens, model_used, chunk_size, etc. (JSON)",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="When upserted"
    )

    @field_validator("embedding", mode="before")
    @classmethod
    def parse_pgvector_embedding(cls, v: Any) -> Any:
        """Parse pgvector string representation to list of floats.

        Supabase returns pgvector columns as strings like '[0.1,0.2,0.3]'.
        This validator converts them to actual Python lists.
        """
        if v is None:
            raise ValueError("embedding is required for RAGVector")
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            # Parse string representation: '[0.1,0.2,0.3]' -> [0.1, 0.2, 0.3]
            v = v.strip()
            if v.startswith("[") and v.endswith("]"):
                v = v[1:-1]  # Remove brackets
            if not v:  # Empty string after removing brackets
                raise ValueError("embedding cannot be empty")
            try:
                return [float(x.strip()) for x in v.split(",") if x.strip()]
            except (ValueError, AttributeError) as e:
                raise ValueError(f"Invalid embedding format: {e}")
        return v

    # Indexes: email_id (FK), content_type
    # Vector index: embedding (pgvector index for similarity search)
