"""
Universal LangGraph Run and State Snapshot utilities for Airtable.

This module provides helper functions for working with the universal
LG Runs and LG State Snapshots tables in Airtable.
"""

import json
from datetime import datetime
from typing import Any, Dict, List, Optional

from lib.integrations.airtable_client import get_airtable_client


def create_lg_run(
    environment: Optional[str] = None,
    input_summary: Optional[str] = None,
    input_payload: Optional[Dict[str, Any]] = None,
    workflow_name: Optional[str] = None,
    user_trigger: Optional[str] = None,
) -> str:
    """
    Create a new LangGraph run entry in Airtable.
    
    Note: Run ID is auto-generated by Airtable formula.
    
    Args:
        environment: Deployment environment (must match Airtable select options)
        input_summary: Summary description of the input
        input_payload: Input data as dictionary (will be JSON stringified)
        workflow_name: Name of the workflow (e.g., 'email_processing', 'form5500')
        user_trigger: Who/what triggered the run (e.g., user email, cron job)
        
    Returns:
        record_id: The Airtable record ID (use this to link snapshots and update)
    """
    client = get_airtable_client()
    
    fields = {}
    
    if environment:
        fields["Environment"] = environment
    
    if input_summary:
        fields["Input Summary"] = input_summary
    
    if input_payload:
        fields["Input Payload"] = json.dumps(input_payload, indent=2)
    
    if workflow_name:
        fields["Workflow Name"] = workflow_name
    
    if user_trigger:
        fields["User/Trigger"] = user_trigger
    
    record = client.create_run(fields)
    return record["id"]


def update_lg_run(
    record_id: str,
    ended_at: Optional[datetime] = None,
    output_payload: Optional[Dict[str, Any]] = None,
    error_message: Optional[str] = None,
    error_payload: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Update an existing LangGraph run.
    
    Args:
        record_id: Airtable record ID
        ended_at: End timestamp
        output_payload: Output data as dictionary
        error_message: Error message if failed
        error_payload: Error details as dictionary
    """
    client = get_airtable_client()
    
    fields: Dict[str, Any] = {}
    
    if ended_at:
        fields["Ended At"] = ended_at.isoformat()
    
    if output_payload:
        fields["Output Payload"] = json.dumps(output_payload, indent=2)
    
    if error_message:
        fields["Error Message"] = error_message
    
    if error_payload:
        fields["Error Payload"] = json.dumps(error_payload, indent=2)
    
    if fields:
        client.update_run(record_id, fields)


def complete_lg_run(
    record_id: str,
    output_payload: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Mark a LangGraph run as completed.
    
    Args:
        record_id: Airtable record ID
        output_payload: Final output data
    """
    update_lg_run(
        record_id,
        ended_at=datetime.utcnow(),
        output_payload=output_payload,
    )


def fail_lg_run(
    record_id: str,
    error_message: str,
    error_payload: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Mark a LangGraph run as failed.
    
    Args:
        record_id: Airtable record ID
        error_message: Error description
        error_payload: Error details
    """
    update_lg_run(
        record_id,
        ended_at=datetime.utcnow(),
        error_message=error_message,
        error_payload=error_payload,
    )


def create_state_snapshot(
    run_record_id: str,
    node: str,
    snapshot_type: str,
    state_envelope: Dict[str, Any],
    snapshot_index: Optional[int] = None,
    payload_schema_ref: Optional[str] = None,
    payload_version: Optional[str] = None,
) -> str:
    """
    Create a state snapshot in Airtable.
    
    Note: Snapshot ID is auto-generated by Airtable formula.
    
    Args:
        run_record_id: Airtable record ID of the LG Run
        node: Node name where snapshot was taken
        snapshot_type: Type of snapshot (e.g., "input", "output", "checkpoint")
        state_envelope: State data as dictionary (will be JSON stringified)
        snapshot_index: Sequential index of this snapshot
        payload_schema_ref: Reference to payload schema
        payload_version: Version of the payload format
        
    Returns:
        record_id: The Airtable record ID of the snapshot
    """
    client = get_airtable_client()
    
    fields = {
        "Run": [run_record_id],  # Link to LG Run record
        "Node": node,
        "Snapshot Type": snapshot_type,
        "State Envelope JSON": json.dumps(state_envelope, indent=2),
    }
    
    if snapshot_index is not None:
        fields["Snapshot Index"] = snapshot_index
    
    if payload_schema_ref:
        fields["Payload Schema Ref"] = payload_schema_ref
    
    if payload_version:
        fields["Payload Version"] = payload_version
    
    # Generate state hash (simple hash of envelope JSON)
    import hashlib
    state_json = json.dumps(state_envelope, sort_keys=True)
    state_hash = hashlib.sha256(state_json.encode()).hexdigest()[:16]
    fields["State Hash"] = state_hash
    
    record = client.create_snapshot(fields)
    return record["id"]


def get_lg_run(record_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve a LangGraph run by Airtable record ID.
    
    Args:
        record_id: Airtable record ID
        
    Returns:
        Run record or None if not found
    """
    client = get_airtable_client()
    return client.get_run(record_id)


def get_recent_runs(
    environment: Optional[str] = None,
    limit: int = 50,
) -> List[Dict[str, Any]]:
    """
    Retrieve recent LangGraph runs.
    
    Args:
        environment: Optional filter by environment
        limit: Maximum number of runs to return
        
    Returns:
        List of run records
    """
    client = get_airtable_client()
    return client.list_runs(environment=environment, limit=limit)


def get_snapshots_for_run(run_record_id: str) -> List[Dict[str, Any]]:
    """
    Get all state snapshots for a specific run.
    
    Args:
        run_record_id: Airtable record ID of the run
        
    Returns:
        List of snapshot records sorted by index
    """
    client = get_airtable_client()
    return client.list_snapshots_for_run(run_record_id)


# Helper function to create state envelope
def create_state_envelope(
    workflow_id: str,
    actor: str,
    phase: str,
    payload: Dict[str, Any],
    schema_version: str = "1.0",
) -> Dict[str, Any]:
    """
    Create a universal state envelope.
    
    Args:
        workflow_id: Identifier for the workflow type
        actor: Who/what is performing this action
        phase: Current workflow phase
        payload: The actual state data
        schema_version: Version of the envelope schema
        
    Returns:
        State envelope dictionary
    """
    return {
        "schema_version": schema_version,
        "workflow_id": workflow_id,
        "actor": actor,
        "phase": phase,
        "timestamp": datetime.utcnow().isoformat(),
        "payload": payload,
    }
