"""
Airtable client for LangGraph logging integration.

This module provides a client for interacting with Airtable tables
used for universal LangGraph run tracking and state management.
"""

import os
from typing import Any, Dict, List, Optional

from pyairtable import Api


class AirtableClient:
    """Client for Airtable LangGraph logging tables."""
    
    def __init__(self, api_key: Optional[str] = None, base_id: Optional[str] = None):
        """
        Initialize Airtable client.
        
        Args:
            api_key: Airtable API key (defaults to AIRTABLE_API_KEY env var)
            base_id: Airtable base ID (defaults to AIRTABLE_BASE_ID env var)
        """
        self.api_key = api_key or os.getenv("AIRTABLE_API_KEY")
        self.base_id = base_id or os.getenv("AIRTABLE_BASE_ID")
        
        if not self.api_key:
            raise ValueError("AIRTABLE_API_KEY environment variable or api_key parameter required")
        if not self.base_id:
            raise ValueError("AIRTABLE_BASE_ID environment variable or base_id parameter required")
        
        self.api = Api(self.api_key)
        self.lg_runs_table = self.api.table(self.base_id, "LG Runs")
        self.state_snapshots_table = self.api.table(self.base_id, "LG State Snapshots")
    
    def create_run(self, fields: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a new LG Run record.
        
        Args:
            fields: Dictionary of field values
            
        Returns:
            Created record with ID and fields
        """
        return self.lg_runs_table.create(fields)
    
    def update_run(self, record_id: str, fields: Dict[str, Any]) -> Dict[str, Any]:
        """
        Update an existing LG Run record.
        
        Args:
            record_id: Airtable record ID
            fields: Dictionary of fields to update
            
        Returns:
            Updated record
        """
        return self.lg_runs_table.update(record_id, fields)
    
    def get_run(self, record_id: str) -> Optional[Dict[str, Any]]:
        """
        Get an LG Run record by ID.
        
        Args:
            record_id: Airtable record ID
            
        Returns:
            Record data or None if not found
        """
        try:
            return self.lg_runs_table.get(record_id)
        except Exception:
            return None
    
    def get_run_by_run_id(self, run_id: str) -> Optional[Dict[str, Any]]:
        """
        Get an LG Run record by Run ID field.
        
        Args:
            run_id: Run ID value (auto-generated by Airtable formula)
            
        Returns:
            Record data or None if not found
        """
        formula = f"{{Run ID}} = '{run_id}'"
        records = self.lg_runs_table.all(formula=formula)
        return records[0] if records else None
    
    def list_runs(
        self,
        environment: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        """
        List LG Run records with optional filtering.
        
        Args:
            environment: Filter by environment
            limit: Maximum number of records to return
            
        Returns:
            List of records
        """
        formula = None
        if environment:
            formula = f"{{Environment}} = '{environment}'"
        
        return self.lg_runs_table.all(
            formula=formula,
            max_records=limit,
            sort=["-Created At"]
        )
    
    def create_snapshot(self, fields: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a new State Snapshot record.
        
        Args:
            fields: Dictionary of field values
            
        Returns:
            Created record with ID and fields
        """
        return self.state_snapshots_table.create(fields)
    
    def get_snapshot(self, record_id: str) -> Optional[Dict[str, Any]]:
        """
        Get a State Snapshot record by ID.
        
        Args:
            record_id: Airtable record ID
            
        Returns:
            Record data or None if not found
        """
        try:
            return self.state_snapshots_table.get(record_id)
        except Exception:
            return None
    
    def list_snapshots_for_run(self, run_record_id: str) -> List[Dict[str, Any]]:
        """
        List all State Snapshots for a specific run.
        
        Args:
            run_record_id: Airtable record ID of the run
            
        Returns:
            List of snapshot records
        """
        formula = f"SEARCH('{run_record_id}', ARRAYJOIN({{Run}}))"
        return self.state_snapshots_table.all(
            formula=formula,
            sort=["Snapshot Index"]
        )


# Singleton instance
_airtable_client: Optional[AirtableClient] = None


def get_airtable_client() -> AirtableClient:
    """Get or create the singleton Airtable client instance."""
    global _airtable_client
    if _airtable_client is None:
        _airtable_client = AirtableClient()
    return _airtable_client


def reset_airtable_client() -> None:
    """Reset the singleton Airtable client instance."""
    global _airtable_client
    _airtable_client = None
